[package]
name = "cargo_doc"
version = "0.1.0"
authors = ["Shivani Bhardwaj <shivanib134@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cargo_doc_test"
path = "src/lib.rs"

[dependencies]
